# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NutritionHelper(object):
    def setupUi(self, NutritionHelper):
        NutritionHelper.setObjectName("NutritionHelper")
        NutritionHelper.resize(903, 600)
        self.label = QtWidgets.QLabel(NutritionHelper)
        self.label.setGeometry(QtCore.QRect(30, 30, 591, 531))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(NutritionHelper)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(690, 20, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(NutritionHelper)
        self.pushButton.setGeometry(QtCore.QRect(700, 520, 161, 61))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(NutritionHelper)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(690, 180, 160, 206))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_1.setAutoExclusive(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout_2.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setAutoExclusive(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setAutoExclusive(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setAutoExclusive(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setAutoExclusive(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setAutoExclusive(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_7.setAutoExclusive(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.tableWidget = QtWidgets.QTableWidget(NutritionHelper)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 671, 601))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_file = QtWidgets.QPushButton(NutritionHelper)
        self.pushButton_file.setGeometry(QtCore.QRect(700, 420, 161, 61))
        self.pushButton_file.setObjectName("pushButton_file")
        self.label_still = QtWidgets.QLabel(NutritionHelper)
        self.label_still.setGeometry(QtCore.QRect(690, 140, 151, 41))
        self.label_still.setObjectName("label_still")

        self.retranslateUi(NutritionHelper)
        QtCore.QMetaObject.connectSlotsByName(NutritionHelper)

    def retranslateUi(self, NutritionHelper):
        _translate = QtCore.QCoreApplication.translate
        NutritionHelper.setWindowTitle(_translate("NutritionHelper", "Widget"))
        self.label.setText(_translate("NutritionHelper", "TextLabel"))
        self.label_2.setText(_translate("NutritionHelper", "How many foods are there?"))
        self.pushButton.setText(_translate("NutritionHelper", "Start"))
        self.checkBox_1.setText(_translate("NutritionHelper", "CheckBox"))
        self.checkBox_2.setText(_translate("NutritionHelper", "CheckBox"))
        self.checkBox_3.setText(_translate("NutritionHelper", "CheckBox"))
        self.checkBox_4.setText(_translate("NutritionHelper", "CheckBox"))
        self.checkBox_5.setText(_translate("NutritionHelper", "CheckBox"))
        self.checkBox_6.setText(_translate("NutritionHelper", "CheckBox"))
        self.checkBox_7.setText(_translate("NutritionHelper", "CheckBox"))
        self.pushButton_file.setText(_translate("NutritionHelper", "Open File"))
        self.label_still.setText(_translate("NutritionHelper", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NutritionHelper = QtWidgets.QWidget()
    ui = Ui_NutritionHelper()
    ui.setupUi(NutritionHelper)
    NutritionHelper.show()
    sys.exit(app.exec_())
